### ISSUE TITLE
Settings over iOS reset display value

### ISSUE THREAD

**Issue by nikolasr200** [apla/me.apla.cordova.app-preferences#92]
I notice something weird.
On some simulators Settings seem to work ok,
however, i test them on a ipad mini 4 9.3 and although i change setting (language) and return to the application, when i return back to the settings page, the default setting keeps being selected all over again.

**Comment by jrobichaud** [comment]
We have the same issue on iPhone 6 with iOS 10 (haven't tested on other platform/device).

However it is only a display issue, the value in the preferences is still the one selected before.

**Comment by jrobichaud** [comment]
I made a pull request to fix this issue:
https://github.com/apla/me.apla.cordova.app-preferences/pull/110

**Comment by nikolasr200** [comment]
I m looking forward to checking it !!

**Comment by jrobichaud** [comment]
@nikolasr200 My pull request just got merged. 
@apla, you might want to close this issue.

**Comment by apla** [comment]
@jrobichaud, thank you and I've just published updated plugin version to the `npm`

**Comment by nikolasr200** [comment]
i must be doing something wrong now..
i ve removed the plugin, reinstalled it, but i m getting still the same issue..also, i have removed from .json file the description, tag, but it still gets build on the debug app..
